# services:
#   backend:
#     build: ./Screen-Break-ai/backend
#     container_name: screen-break-ai-backend
#     ports:
#       - "3001:3001"
#     env_file:
#       - ./Screen-Break-ai/backend/server/.env
#     environment:
#       - NODE_TLS_REJECT_UNAUTHORIZED=0
#     dns:
#       - 8.8.8.8
#       - 8.8.4.4
#     # healthcheck:
#     #   test: ["CMD", "curl", "-f", "http://localhost:3001"]
#     #   interval: 30s
#     #   timeout: 10s
#     #   retries: 3
#     #   start_period: 40s
  
#   jenkins:
#     build: ./jenkins
#     container_name: screen-break-ai-jenkins
#     ports:
#       - "8080:8080"
#       # - "50001:50000"
#     volumes:
#       - jenkins_home:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#     environment:
#       - DOCKER_HOST=unix:///var/run/docker.sock
#     # depends_on:
#     #   backend:
#     #     condition: service_healthy

# volumes:
#   jenkins_home:
services:
  backend:
    build: ./Screen-Break-ai/backend
    container_name: screen-break-ai-backend
    ports:
      - "3001:3001"
    env_file:
      - ./Screen-Break-ai/backend/server/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  jenkins:
    build: ./jenkins
    container_name: screen-break-ai-jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock

volumes:
  jenkins_home:
